### ISSUE TITLE
Commit data file

### ISSUE THREAD

**Issue by shinkle-lanl** [pi4-uiuc/IndoorOutdoor#5]
Our .csv file is too large and we are having trouble committing it.

**Comment by klajbor2** [comment]
just as an update to this issue: we're working on cleaning this up at Ran's workstation

**Comment by klajbor2** [comment]
a good idea for the future is to put such files in the .gitignore

**Comment by klajbor2** [comment]
We've resolved this, yay! @ranji418 and I used the git filter-branch command to remove the big files.

This "alters history", so in the future, you should always use with supreme care (for example, we made backups of the most important files outside of the git repo). This is a "only" in emergencies thing.  It was also made easier since the things we wanted to remove from the commit history had not been committed to the github repo yet.

For the future, big files and files you don't want to commit should be added to the .gitignore file.

**Comment by klajbor2** [comment]
At the end I assigned the person who opened this issue, and the people who worked on this. Make sure you assign people on the right half pane when you create an issue.

I'll go ahead and close this issue as resolved.
